apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
  # 削除時にリソースも削除
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/penti-nameko/portfolio  # ← リポジトリURLに変更
    targetRevision: main
    path: k8s/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: reeldevjp

  syncPolicy:
    automated:
      prune: true          # Git から消えたリソースを自動削除
      selfHeal: true       # 手動変更を自動的に戻す
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
