apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# 本番: replica 数を増やす
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: reeldevjp-frontend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: reeldevjp-bff

# イメージタグは ArgoCD Image Updater または CI で上書き
images:
  - name: ghcr.io/penti-nameko/portfolio-frontend
    newTag: "cef3805c655c614e02795fb3cef1084b5703382a"
  - name: ghcr.io/penti-nameko/portfolio-bff
    newTag: "cef3805c655c614e02795fb3cef1084b5703382a"
  - name: ghcr.io/penti-nameko/reeldevjp-frontend
    newTag: "cef3805c655c614e02795fb3cef1084b5703382a"
  - name: ghcr.io/penti-nameko/reeldevjp-bff
    newTag: "cef3805c655c614e02795fb3cef1084b5703382a"
