apiVersion: v1
kind: ConfigMap
metadata:
  name: reeldevjp-config
data:
  QIITA_USER: "riel-hosiduki"                         # ← Qiita ユーザー名に変更
  CORS_ORIGIN: "https://reeldev.jp"            # ← 本番ドメインに変更
