apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - bff-deployment.yaml
  - bff-service.yaml
  - ingress.yaml

namespace: reeldevjp