apiVersion: v1
kind: Secret
metadata:
  name: reeldevjp-secrets
  namespace: reeldevjp
type: Opaque
stringData:
  QIITA_USER: "riel-hosiduki"
  QIITA_TOKEN: "your_token_here" # ← ここに本物のトークン文字列を入れる
  CORS_ORIGIN: "http://localhost:5173" # ※本番環境のURLがある場合はそれに書き換えてもOK
  PORT: "3001"
